# Generated by Django 2.1.1 on 2018-09-29 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=20)),
                ('sell_signal', models.IntegerField(default=0)),
                ('buy_signal', models.IntegerField(default=0)),
                ('hold_signal', models.IntegerField(default=0)),
                ('data', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Stock')),
            ],
        ),
    ]
