# Generated by Django 2.1.1 on 2018-09-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='data',
        ),
        migrations.AddField(
            model_name='stock',
            name='time_series_prices',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='time_series_plot',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buy_signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='hold_signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
