# Generated by Django 2.1.1 on 2018-09-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_auto_20180929_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_series_plot', models.FloatField(default=0.0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Stock')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockmodel',
            name='time_series_plot',
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='buy_signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='hold_signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='sell_signal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
