# Generated by Django 2.1.1 on 2018-09-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_auto_20180929_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='time_series_prices',
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='time_series_plot',
        ),
        migrations.AddField(
            model_name='stockmodel',
            name='health',
            field=models.CharField(default='red', max_length=200),
        ),
    ]
